---
libraries:
  Anime:
    metadata_files:
      # - repo: Monogatari.yml

settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: false
  asset_depth: 0
  create_asset_folders: false
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: true
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: sync
  minimum_items: 1
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  show_unmanaged: true
  show_filtered: false
  show_options: false
  show_missing: false
  show_missing_assets: true
  save_report: false
  tvdb_language: eng
  ignore_ids: null
  ignore_imdb_ids: null
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_exclude_user: null
  playlist_report: false
  verify_ssl: true
  custom_repo: https://github.com/unleashurgeek/home-ops/tree/main/kubernetes/main/apps/media/kometa/app/custom/
  check_nightly: false
  show_unconfigured: true
  playlist_exclude_users: null

plex:
  url: http://plex.media:32400
  token: <<PLEX_API_KEY>>
  timeout: 60
  clean_bundles: false
  empty_trash: false
  optimize: false

tmdb:
  apikey: <<TMDB_API_KEY>>
  language: en
  cache_expiration: 60
  region: null