---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kavita
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: ${APP_UID}
            runAsGroup: ${APP_GID}
            fsGroup: ${APP_GID}
            runAsNonRoot: true
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups: [44, 105, 10000]

        containers:
          main:
            image:
              repository: ghcr.io/kareadita/kavita
              tag: 0.8.3@sha256:6d6bf8e9be270637d6741d5204d8a18c4def8fea8cbefe7215c898e470e5ca92
            resources:
              requests:
                cpu: 15m
                memory: 300Mi
              limits:
                memory: 1Gi

    service:
      main:
        ports:
          http:
            port: &port 5000


    ingress:
      main:
        enabled: true
        className: internal
        hosts:
          - host: &host "{{ .Release.Name }}.kyle.fail"
            paths:
              - path: /
                service:
                  name: main
                  port: *port
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: kavita
        globalMounts:
          - path: /kavita/config
      media:
        type: nfs
        server: tank.kyle.fail
        path: /mnt/tank/media
        globalMounts:
          - path: /media
            readOnly: true