---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-movies-cache
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-block
