---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./intel-device-plugins/ks.yaml
  - ./node-feature-discovery/ks.yaml
components:
  - ../../components/common
patches:
  - patch: |
      - op: add
        path: /metadata/labels/k8tz.io~1controller-namespace
        value: "true"
    target:
      kind: Namespace
