apiVersion: v1
kind: Secret
metadata:
    name: external-dns-bind-crd-secret
data:
    EXTERNAL_DNS_RFC2136_TSIG_SECRET: ENC[AES256_GCM,data:A4DWjQLyCThHgtuE6kCRFrFKA300mSe+eCfG9NG+ECkwlepyBqYLu3ud6ZznNnHyUPrSw6HoYNRGH2sV,iv:rTSOP0rKPgvAB9ujpaA/fFJ7Ksz7CPIrqJE3yBaenTw=,tag:xYqxZl93/YQt8g4cIlALfg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rss899lzcafjv5y8ve8cj4urhqfyypwrlqua2jmeyusmkdmugdxqsluwyl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZGZRK2JwUWtrQWpCRlBy
            VkpJa1JPaUZQSHdBZWVjdE5vc09ZVTRPdzNvCitJdG5icm9ySFhnVVB5Rkk0aTFx
            SE4wbXArTTVremZmdkxjUTdYMEF3UUUKLS0tIGJlV0V0aTZGeWhuOXdQd21aMzVO
            ayttc0ptbUtKenkrL0IvUlNJMGtLUmsKobPvLR5ozT9Wqr6TfnY/Ym4TNkN89G5J
            bzCMcj3BnULEqf/lw6ZNAPOrlWdv5amrmxfebnEePXdmjiTyqSCGfQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zt22uns634n9qxy34jjjp86cw5ruynpngge0ypdere8kq40ysylqh6ce5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMVEzS0dKTUhab3pYNGhJ
            QkI3UU00SkhJMXAvekw5LzkvTmdwTXg5RVFjCjVJUFJXS1NwNlZWMHZPVXNBbHRY
            SEpnSlp0U1p1WXg2VExwMkQ5NWpoS00KLS0tIGFDNmlMZVhWL0x1L2tsc0l3WTRI
            Tkcxb25QanpsK1RvNVdrVzZiem5iTWsKQt0ifJ/rQZyh8LGK1tdeVmVdTG1RVMGy
            UcyPwYV4VgqfhkoYqBfX+3ttLRLw+/yUl4YGj5Hhy95+OSL3655XTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-26T07:48:58Z"
    mac: ENC[AES256_GCM,data:w3KXz9tjggZM9zbs1dceIRJz1iOoV+qPHfcpCrdlhqC92dDMzzZWf9aUZZNBxONKIuOCxjx9CtGIDKFKvEcYXJ7UZWGHCQWj7N/SdDZUTz8t9jRBmCJNw6nbPx2rtgJwlvYatH2ADRtmMIoyMgd51fV7wRPqrAx9DCgjS7ZuWvM=,iv:qTMBLfLWl/19far01wTHbAnQfJtb7pv9SY3HAlTm0nk=,tag:2EVddj57GzlYj8/bjiNfbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
