---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qbittorrent
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: qbittorrent-secret
    template:
      engineVersion: v2
      data:
        VPN_ENDPOINT_IP: "{{ .QBIT_ENDPOINT_IP }}"
        WIREGUARD_PUBLIC_KEY: "{{ .QBIT_WIREGUARD_PUBLIC_KEY }}"
        WIREGUARD_PRIVATE_KEY: "{{ .QBIT_WIREGUARD_PRIVATE_KEY }}"
        WIREGUARD_ADDRESSES: "{{ .QBIT_WIREGUARD_ADDRESSES }}"
  dataFrom:
    - extract:
        key: proton-vpn