---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          configmap.reloader.stakater.com/reload: qbittorrent-scripts
          secret.reloader.stakater.com/reload: qbittorrent-secret

        pod:
          securityContext:
            fsGroup: ${APP_GID}
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 10000

        containers:
          main:
            nameOverride: qbittorrent
            image:
              repository: ghcr.io/onedr0p/qbittorrent
              tag: 4.5.2@sha256:0efdd8d3ef3964d658d78ea7789efa285e9c01d1d436da2903cfde462a7fe67a
            env:
              UMASK: "022"
              QBITTORRENT__PORT: &port 8080
              QBT_Preferences__WebUI__AlternativeUIEnabled: false
              QBT_Preferences__WebUI__AuthSubnetWhitelistEnabled: true
              QBT_Preferences__WebUI__AuthSubnetWhitelist: |-
                10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
              QBT_Preferences__WebUI__LocalHostAuth: false
              QBT_Preferences__WebUI__UseUPNP: false
              QBT_BitTorrent__Session__BTProtocol: TCP
              QBT_BitTorrent__Session__SubcategoriesEnabled: true
              QBT_BitTorrent__Session__DefaultSavePath: /media/downloads/torrent/complete
              QBT_BitTorrent__Session__TempPath: /media/downloads/torrent/temp
              QBT_BitTorrent__Session__TempPathEnabled: true
              QBT_BitTorrent__Session__DisableAutoTMMByDefault: false
              QBT_BitTorrent__Session__DisableAutoTMMTriggers__CategorySavePathChanged: false
              QBT_BitTorrent__Session__DisableAutoTMMTriggers__DefaultSavePathChanged: false
              QBT_BitTorrent__Session__MaxConnections: -1
              QBT_BitTorrent__Session__MaxConnectionsPerTorrent: -1
              QBT_BitTorrent__Session__MaxUploads: -1
              QBT_BitTorrent__Session__MaxUploadsPerTorrent: -1
              QBT_BitTorrent__Session__QueueingSystemEnabled: false
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v2/app/version
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 49m
                memory: 1024Mi
              limits:
                memory: 8192Mi
            securityContext:
              runAsUser: ${APP_UID}
              runAsGroup: ${APP_GID}
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

          gluetun:
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: latest@sha256:450a487b23cd460da99b025b32b22fbccd41e7f3a0b083d34326d5a4c88519b0
            env:
              VPN_SERVICE_PROVIDER: custom
              VPN_TYPE: wireguard
              VPN_INTERFACE: wg0
              VPN_ENDPOINT_PORT: 51820
              VPN_PORT_FORWARDING: on
              VPN_PORT_FORWARDING_PROVIDER: protonvpn
              FIREWALL_INPUT_PORTS: *port
              FIREWALL_OUTBOUND_SUBNETS: 10.96.0.0/12,10.244.0.0/16 # Allow access to k8s subnets
            envFrom:
              - secretRef:
                  name: qbittorrent-secret
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
              allowPrivilegeEscalation: false

          port-forward:
            image:
              repository: ghcr.io/bjw-s/gluetun-qb-port-sync
              tag: v0.0.1
            env:
              GLUETUN_CONTROL_SERVER_HOST: localhost
              GLUETUN_CONTROL_SERVER_PORT: 8000
              QBITTORRENT_HOST: localhost
              QBITTORRENT_WEBUI_PORT: *port
              CRON_ENABLED: true
              CRON_SCHEDULE: "*/5 * * * *"
              LOG_TIMESTAMP: false
            securityContext:
              runAsUser: ${APP_UID}
              runAsGroup: ${APP_GID}
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        className: internal
        hosts:
          - host: &host qbit.kyle.fail
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent
        advancedMounts:
          main:
            main:
              - path: /config
      scripts:
        type: configMap
        name: qbittorrent-scripts
        defaultMode: 0775
        advancedMounts:
          main:
            main:
              - path: /scripts/completed.sh
                subPath: completed.sh
                readOnly: true
      media:
        type: nfs
        server: tank.kyle.fail
        path: /mnt/tank/media
        advancedMounts:
          main:
            main:
              - path: /media