---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: thanos
spec:
  interval: 30m
  chart:
    spec:
      chart: thanos
      version: 15.1.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      registry: quay.io
      repository: thanos/thanos
      tag: v0.34.1

    objstoreConfig:
      type: s3
      config:
        insecure: false

    queryFrontend:
      enabled: true
      replicaCount: 2
      config: &config |-
        type: REDIS
        config:
          addr: >-
            redis-node-0.redis-headless.database.svc.cluster.local:26379,
            redis-node-1.redis-headless.database.svc.cluster.local:26379,
            redis-node-2.redis-headless.database.svc.cluster.local:26379
          db: 13
          master_name: redis-master
      ingress:
        enabled: true
        ingressClassName: internal
        hostname: &host thanos.kyle.fail
        tls: true
        extraTls:
          - hosts:
              - *host

    query:
      enabled: true
      replicaCount: 2
      replicaLabel: [__replica__]
      dnsDiscovery:
        sidecarsService: kube-prometheus-stack-thanos-discovery
        sidecarsNamespace: monitoring
      stores: []
      resources:
        requests:
          cpu: 15m
          memory: 64M

    bucketweb:
      enabled: true
      replicaCount: 2
      resources:
        requests:
          cpu: 15m
          memory: 64M

    compactor:
      enabled: true
      extraFlags:
        - "--compact.concurrency=4"
        - --delete-delay=30m
      retentionResolutionRaw: 14d
      retentionResolution5m: 30d
      retentionResolution1h: 90d
      resources:
        requests:
          cpu: 15m
          memory: 204M
      persistence:
        enabled: true
        storageClass: "local-hostpath"
        size: 15Gi

    storegateway:
      enabled: true
      replicaCount: 2
      config: *config
      resources:
        requests:
          cpu: 24m
          memory: 204M
      persistence:
        enabled: true
        storageClass: "local-hostpath"
        size: 1Gi

    ruler:
      enabled: true
      replicaCount: 2
      replicaLabel: __replica__
      alertmanagers:
        - http://alertmanager.monitoring.svc.cluster.local:9093
      clusterName: ${CLUSTER_NAME}
      config: |-
        groups:
          - name: PrometheusWatcher
            rules:
              - alert: PrometheusDown
                annotations:
                  summary: A Prometheus has disappeared from Prometheus target discovery
                expr: absent(up{job="kube-prometheus-stack-prometheus"})
                for: 5m
                labels:
                  severity: critical
      persistence:
        enabled: true
        storageClass: "local-hostpath"
        size: 512Mi
      resources:
        requests:
          cpu: 23m
          memory: 128M
        limits:
          memory: 256M

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  valuesFrom:
    - targetPath: objstoreConfig.config.bucket
      kind: Secret
      name: thanos-secret
      valuesKey: S3_BUCKET
    - targetPath: objstoreConfig.config.endpoint
      kind: Secret
      name: thanos-secret
      valuesKey: S3_HOST
    - targetPath: objstoreConfig.config.region
      kind: Secret
      name: thanos-secret
      valuesKey: S3_REGION
    - targetPath: objstoreConfig.config.access_key
      kind: Secret
      name: thanos-secret
      valuesKey: S3_ACCESS_KEY
    - targetPath: objstoreConfig.config.secret_key
      kind: Secret
      name: thanos-secret
      valuesKey: S3_SECRET_KEY