---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frigate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: frigate-secret
    template:
      engineVersion: v2
      data:
        FRIGATE_CAM1_USER: "{{ .FRIGATE_CAM1_USER }}"
        FRIGATE_CAM1_PASSWORD: "{{ .FRIGATE_CAM1_PASSWORD }}"
        FRIGATE_CAM2_USER: "{{ .FRIGATE_CAM2_USER }}"
        FRIGATE_CAM2_PASSWORD: "{{ .FRIGATE_CAM2_PASSWORD }}"
  dataFrom:
    - extract:
        key: frigate