---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-tunnel
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflared-tunnel-secret
    template:
      data:
        credentials.json: |
          {
            "AccountTag": "{{ .ACCOUNT_TAG }}",
            "TunnelSecret": "{{ .TUNNEL_SECRET }}",
            "TunnelID": "c43ec453-010f-42b0-b37c-e29c7aaec41b"
          }
  dataFrom:
    - extract:
        key: cloudflare
