---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dashbrr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: dashbrr-secret
    template:
      engineVersion: v2
      data:
        DASHBRR__DB_TYPE: postgres
        DASHBRR__DB_NAME: &dbName dashbrr
        DASHBRR__DB_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        DASHBRR__DB_PORT: "5432"
        DASHBRR__DB_USER: &dbUser "{{ .DASHBRR_POSTGRES_USER }}"
        DASHBRR__DB_PASSWORD: &dbPass "{{ .DASHBRR_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        DASHBRR_PLEX_API_KEY: "{{ .PLEX_TOKEN }}"
        DASHBRR_SONARR_TV_API_KEY: "{{ .SONARR_TV_API_KEY }}"
        DASHBRR_SONARR_ANIME_API_KEY: "{{ .SONARR_ANIME_API_KEY }}"
        DASHBRR_RADARR_MOVIES_API_KEY: "{{ .RADARR_MOVIES_API_KEY }}"
        DASHBRR_RADARR_HQ_API_KEY: "{{ RADARR_HQ_API_KEY }}"
        DASHBRR_RADARR_ANIME_API_KEY: "{{ .RADARR_ANIME_API_KEY }}"
        DASHBRR_OVERSEERR_API_KEY: "{{ .OVERSEERR_API_KEY }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: dashbrr
    - extract:
        key: plex
    - extract:
        key: sonarr
    - extract:
        key: radarr
    - extract:
        key: overseerr