---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

set:
  - pipefail
shopt:
  - globstar

includes:
  talos: .taskfiles/talos/Taskfile.yaml
  bootstrap: .taskfiles/bootstrap/Taskfile.yaml
  sops: .taskfiles/sops/Taskfile.yaml
  flux: .taskfiles/flux/Taskfile.yaml
  kube: .taskfiles/kube/Taskfile.yaml
  volsync: .taskfiles/volsync/Taskfile.yaml

vars:
  K8S_DIR: "{{.ROOT_DIR}}/kubernetes"
  KUBECONFIG: "{{.K8S_DIR}}/kubeconfig"
  TALOSCONFIG: "{{.K8S_DIR}}/talos/clusterconfig/talosconfig"

env:
  KUBECONFIG: "{{.KUBECONFIG}}"
  TALOSCONFIG: "{{.TALOSCONFIG}}"

tasks:
  default:
    silent: true
    cmd: task --list

  noop:
    internal: true
    silent: true
    cmd: noop() { :; }
