---
version: "3"

env:
  SOPS_AGE_KEY_FILE: "{{.ROOT_DIR}}/age.key"
  TASK_X_ANY_VARIABLES: "1"

vars:
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"

includes:
  sops: .task/sops
  talos: .task/talos
  k8s: .task/k8s
  cluster: .task/cluster

tasks:
  default:
    silent: true
    cmds:
      - task -l