---
version: "3"

env:
  SOPS_AGE_KEY_FILE: "{{.ROOT_DIR}}/age.key"

vars:
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"

includes:
  sops: .task/sops
  talos: .task/talos
  k8s: .task/k8s
  cluster: .task/cluster
  flux: .task/flux
  rook: .task/rook
  volsync: .task/volsync
  secret: .task/secret

tasks:
  default:
    silent: true
    cmds:
      - task -l