---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  sync:
    desc: Sync an ExternalSecret for a cluster
    summary: |
      Args:
        cluster: Cluster to run command against (required)
        ns: Namespace the externalsecret is in (default: default)
        secret: Secret to sync (required)
    requires:
      vars: [cluster, ns, secret]
    cmd: kubectl -n {{.ns}} annotate externalsecret {{.secret}} force-sync=$(date +%s) --overwrite
    preconditions:
      - { msg: "ExternalSecret not found",       sh: "kubectl -n {{.ns}} get externalsecret {{.secret}}" }
