---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: qbtools
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        enabled: false

      tagging:
        type: cronjob

        cronjob:
          schedule: "@hourly"
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1

        pod:
          restartPolicy: OnFailure
          securityContext: &podSecurityContext
            runAsUser: ${APP_UID}
            runAsGroup: ${APP_GID}
            runAsNonRoot: true

        initContainers:
          main:
            image: &image
              repository: ghcr.io/buroa/qbtools
              tag: v0.19.15@sha256:4145020bab12b2ed892f548c2812c4979793def80dce5f907e49640329e54933
            args: [
              "tagging",
              "--added-on",
              "--expired",
              "--last-activity",
              "--sites",
              "--unregistered",
              "--server", "qbittorrent.downloads.svc.cluster.local",
              "--port", "8080",
              "--config", "/config/config.yaml"
            ]
            resources: &resources
              requests:
                memory: 128Mi
                cpu: 25m
              limits:
                memory: 256Mi
            securityContext: &containerSecurityContext
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

        containers:
          unregistered:
            image: *image
            args: [
              "prune",
              "--exclude-category", "manual",
              "--include-tag", "unregistered",
              # "--dry-run",
              "--server", "qbittorrent.downloads.svc.cluster.local",
              "--port", "8080"
            ]
            resources: *resources
            securityContext: *containerSecurityContext

      reannounce:
        pod:
          securityContext: *podSecurityContext
        containers:
          main:
            image: *image
            args: [
              "reannounce",
              "--process-seeding",
              "--server", "qbittorrent.downloads.svc.cluster.local",
              "--port", "8080"
            ]
            resources: *resources
            securityContext: *containerSecurityContext

    persistence:
      config-file:
        type: configMap
        name: qbtools-configmap
        globalMounts:
          - path: /config/config.yaml
            subPath: config.yaml
            readOnly: true

    service:
      main:
        enabled: false