---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app external-dns-bind
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: registry.k8s.io/external-dns/external-dns
              tag: v0.14.1@sha256:7bb4c52748dec4fa2df1a8df7b94355c9677c70378cfe555ee4eb9a476409f0c
            env:
              EXTERNAL_DNS_RFC2136_HOST: 192.168.2.58
              EXTERNAL_DNS_RFC2136_PORT: "53"
              EXTERNAL_DNS_RFC2136_ZONE: kyle.fail
              EXTERNAL_DNS_RFC2136_TSIG_AXFR: "true"
              EXTERNAL_DNS_RFC2136_TSIG_KEYNAME: externaldns-key
              EXTERNAL_DNS_RFC2136_TSIG_SECRET_ALG: hmac-sha256
            envFrom:
              - secretRef:
                  name: external-dns-bind-secret
            args:
              - --domain-filter=kyle.fail
              - --interval=1m
              - --log-format=text
              - --log-level=info
              - --metrics-address=:7979
              - --policy=sync
              - --provider=rfc2136
              - --registry=txt
              - --source=ingress
              - --source=service
              - --txt-owner-id=default
              - --txt-prefix=k8s.
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 7979
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 64Mi

        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true

    serviceAccount:
      create: true
      name: *app

    service:
      main:
        ports:
          http:
            port: *port

    serviceMonitor:
      main:
        enabled: true