apiVersion: v1
kind: Secret
metadata:
    name: external-dns-bind-secret
data:
    BIND_RNDC_KEY: ENC[AES256_GCM,data:mgAUC+M2aX8jyx8P8uQQVk4TiF4/a+Ly+NylDiWII/LH57Jpgqp8g3K3t/PGTVyYsZ/vrJdN9UG92Ywp,iv:16Z78sAWsi/FbMwcpAIYp+gW95/hETX/Ov4GhZyaUBc=,tag:XvQE/pFOZRorFve5HLahYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rss899lzcafjv5y8ve8cj4urhqfyypwrlqua2jmeyusmkdmugdxqsluwyl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZGZRK2JwUWtrQWpCRlBy
            VkpJa1JPaUZQSHdBZWVjdE5vc09ZVTRPdzNvCitJdG5icm9ySFhnVVB5Rkk0aTFx
            SE4wbXArTTVremZmdkxjUTdYMEF3UUUKLS0tIGJlV0V0aTZGeWhuOXdQd21aMzVO
            ayttc0ptbUtKenkrL0IvUlNJMGtLUmsKobPvLR5ozT9Wqr6TfnY/Ym4TNkN89G5J
            bzCMcj3BnULEqf/lw6ZNAPOrlWdv5amrmxfebnEePXdmjiTyqSCGfQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zt22uns634n9qxy34jjjp86cw5ruynpngge0ypdere8kq40ysylqh6ce5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMVEzS0dKTUhab3pYNGhJ
            QkI3UU00SkhJMXAvekw5LzkvTmdwTXg5RVFjCjVJUFJXS1NwNlZWMHZPVXNBbHRY
            SEpnSlp0U1p1WXg2VExwMkQ5NWpoS00KLS0tIGFDNmlMZVhWL0x1L2tsc0l3WTRI
            Tkcxb25QanpsK1RvNVdrVzZiem5iTWsKQt0ifJ/rQZyh8LGK1tdeVmVdTG1RVMGy
            UcyPwYV4VgqfhkoYqBfX+3ttLRLw+/yUl4YGj5Hhy95+OSL3655XTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-31T16:48:05Z"
    mac: ENC[AES256_GCM,data:5Jtgkt2hV7xnac6vHifeYbe//8+T/qTBUVi+3Y5y5VoHAHrbYTKNXYfeO+2aXXKkSczvuYigHwuOx3BcSdCHf5X/5vuguNF9T79A4kprxlQQ4mq0huSyF7IxF78DfoaftsQKDF1c07sZ9quzpwGLZxp6pmZqndCM8k/lvZ0RNKY=,iv:7a88oUu4IM+AJbB8FWG3w6QzOQuilAD38mx7T9EL9Wo=,tag:TxPK0PRfiVFZr0fAmSlqyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
