---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres16
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1-12
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    storageClass: local-hostpath
  superuserSecret:
    name: cloudnative-pg-secret
  enableSuperuserAccess: true
  # NOTE: For initial cluster bootstrap, this needs to be commented out.
  # After initial bootstrap, want previous-cluster == current-cluster in the event that we
  # bootstrap the cluster again (IE: if we nuke the k8s cluster). Increment on migrations
  bootstrap:
    recovery:
      source: &previous-cluster postgres16-v1
  postgresql:
    parameters:
      max_connections: "600"
      max_slot_wal_keep_size: 10GB
      shared_buffers: 512MB
  resources:
    requests:
      memory: 2Gi
      cpu: 500m
    limits:
      memory: 4Gi
  monitoring:
    enablePodMonitor: false # TODO: prometheus
    podMonitorMetricRelabelings:
      - action: replace
        sourceLabels: [cluster]
        targetLabel: cnpg_cluster
      - regex: cluster
        action: labeldrop
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: &s3-path s3://main-cloudnative-pg/
      endpointURL: &s3-endpoint https://s3.kyle.fail
      serverName: &current-cluster postgres16-v1
      s3Credentials: &s3-creds
        accessKeyId:
          name: cloudnative-pg-secret
          key: aws-access-key-id
        secretAccessKey:
          name: cloudnative-pg-secret
          key: aws-secret-access-key
  externalClusters:
    - name: *previous-cluster
      barmanObjectStore:
        wal:
          compression: bzip2
          maxParallel: 8
        destinationPath: *s3-path
        endpointURL: *s3-endpoint
        s3Credentials: *s3-creds