---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ext-postgres-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: ext-postgres-operator
      version: 1.2.6
      sourceRef:
        kind: HelmRepository
        name: ext-postgres-operator
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    podAnnotations:
      reloader.stakater.com/auto: "true"

    existingSecret: ext-postgres-operator-secret

    resources:
      requests:
        cpu: 5m
        memory: 32M
      limits:
        memory: 100M