---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  "*-ks":
    desc: Render a Flux Kustomizations [DIR=required] [NAME] [SRC]
    vars:
      OPERATION: "{{index .MATCH 0}}"
      OPERATION_ARGS: |-
        {{if eq .OPERATION "apply"}} --server-side --field-manager=kustomize-controller{{end}}
      KS_DIR: "{{.K8S_DIR}}/apps/{{.DIR}}"
    requires:
      vars:
        - DIR
    preconditions:
      - '[[ "{{.OPERATION}}" == "build" || "{{.OPERATION}}" == "apply" || "{{.OPERATION}}" == "delete" ]]'
      - which kubectl flux-local
      - test -d {{.KS_DIR}}
    cmds:
      - flux-local build ks --all-namespaces {{.NS}} --path {{.KS_DIR}} {{.NAME}}
        | yq -
        {{ if or (eq .OPERATION "apply") (eq .OPERATION "delete") -}}
        | kubectl {{.OPERATION}} {{- .OPERATION_ARGS}} --filename -
        {{ end }}

  "*-ks-all":
    desc: Suspend or resume all Flux Kustomizations
    vars:
      STATE: '{{index .MATCH 0}}'
    preconditions:
      - '[[ "{{.STATE}}" == "suspend" || "{{.STATE}}" == "resume" ]]'
      - which flux kubectl
    cmds:
      - kubectl get ns -o jsonpath='{.items[*].metadata.name}' | xargs -n1 flux {{.STATE}} ks --all --namespace

  reconcile:
    desc: Force update Flux to pull in changes from your Git repository
    cmds:
      - flux get ks --no-header -n flux-system | awk '{print $1, $2}' | xargs -L1 bash -c 'flux reconcile ks -n flux-system $0'
      - flux get ks --all-namespaces --no-header | awk '{print $1, $2}' | xargs -L1 bash -c 'flux reconcile ks -n $0 $1'
    preconditions:
      - which flux kubectl

  hr-restart:
    desc: Restart all failed Helm Releases
    cmds:
      - kubectl get hr --all-namespaces | grep False | awk '{print $1, $2}' | xargs -L1 bash -c 'flux suspend hr ks -n $0 $1'
      - kubectl get hr --all-namespaces | grep False | awk '{print $1, $2}' | xargs -L1 bash -c 'flux resume hr ks -n $0 $1'
    preconditions:
      - which flux kubectl
