---
# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
clusterName: ${clusterName}
endpoint: "https://${clusterVIP}:6443" # TODO: change to url after dns reconfiguration
allowSchedulingOnControlPlanes: true

# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.6.1

# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.29.0

cniConfig:
  name: none

additionalApiServerCertSans: &san
  - ${clusterVIP}
  - ${clusterName}.${clusterDNSSuffix}
  - "127.0.0.1" # KubePrism
additionalMachineCertSans: *san

nodes:
  - &it12 # GEEKOM IT12, i7-12650H, nvme + ssd storage
    hostname: augustus
    ipAddress: 192.168.10.20
    controlPlane: true
    installDiskSelector:
      size: "<= 600GB"
      type: ssd
    disableSearchDomain: true
    networkInterfaces:
      - &it12-net
        deviceSelector:
          driver: igc # Ethernet Controller I225-V
        addresses:
          - 192.168.10.20
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.10.1
        dhcp: false
        vip:
          ip: ${clusterVIP}
    nameservers:
      - 192.168.2.58
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/i915-ucode
            - siderolabs/intel-ucode
            - siderolabs/thunderbolt
    patches:
      # kubelet extra mount config
      - |-
        machine:
          kubelet:
            extraMounts:
              - destination: /var/mnt/nvme
                type: bind
                source: /var/mnt/nvme
                options:
                  - rbind
                  - rshared
                  - rw

  - <<: *it12
    hostname: nero
    ipAddress: 192.168.10.21
    networkInterfaces:
      - <<: *it12-net
        addresses:
          - 192.168.10.21

  - <<: *it12
    hostname: titus
    ipAddress: 192.168.10.22
    networkInterfaces:
      - <<: *it12-net
        addresses:
          - 192.168.10.22

controlPlane:
  schematic:
    customization:
      extraKernelArgs:
        - net.ifnames=0

  patches:
    # NTP
    - |-
      machine:
        time:
          disabled: false
          servers:
            - time.cloudflare.com

    # Configure cluster loopback
    - |-
      machine:
        network:
          extraHostEntries:
            - ip: ${clusterVIP}
              aliases:
                - ${clusterName}.${clusterDNSSuffix}

    # Disable kube-proxy
    - |-
      cluster:
        proxy:
          disabled: true

    # ETCD configuration
    - |-
      cluster:
        etcd:
          advertisedSubnets:
            - 192.168.10.0/24

    # Configure containerd
    - |-
      machine:
        files:
          - op: create
            path: /etc/cri/conf.d/20-customization.part
            permissions: 0o644
            content: |
              [plugins."io.containerd.grpc.v1.cri"]
                enable_unprivileged_ports = true
                enable_unprivileged_icmp = true
              [plugins."io.containerd.grpc.v1.cri".containerd]
                discard_unpacked_layers = false

    # Kubelet configuration
    - |-
      machine:
        kubelet:
          extraArgs:
            feature-gates: GracefulNodeShutdown=true
            rotate-server-certificates: "true"
          extraConfig:
            maxPods: 150
          nodeIP:
            validSubnets:
              - 192.168.10.0/24

    # Configure nfs mount options
    - |-
      machine:
        files:
          - op: overwrite
            path: /etc/nfsmount.conf
            permissions: 0o644
            content: |
              [ NFSMount_Global_Options ]
              nfsvers=4.2
              hard=True
              noatime=True
              nodiratime=True
              rsize=131072
              wsize=131072
              nconnect=8

    # Custom sysctls
    - |-
      machine:
        sysctls:
          fs.inotify.max_user_watches: "1048576"
          fs.inotify.max_user_instances: "8192"