clusterName: ENC[AES256_GCM,data:NpaQJg==,iv:TT4GkeCh5DSo299bGPJDv266S3l95HB5yH9J37OrO44=,tag:RyUN0vaKpXrS/Y72c5cLMg==,type:str]
clusterVIP: ENC[AES256_GCM,data:vUp+iN/crlHvybkgQQ==,iv:06xJOOEF+CSeP4MaGZ37D5K+axTgVGYlX02v8/eWI1g=,tag:3GYHpWhO5+bkudEhBk9/nQ==,type:str]
clusterDNSSuffix: ENC[AES256_GCM,data:FFwMSRJrbiRJHC6eug==,iv:/MCwTnUKGbiINqzs+PzeCo2YMxnR74lKJnvMHzaUSiA=,tag:LOaqHyd+EZD7/+5Zjwhb1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rss899lzcafjv5y8ve8cj4urhqfyypwrlqua2jmeyusmkdmugdxqsluwyl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYVZVNDBWY3kyR1RIYjlV
            TElhb29PelROZmNYTlRicTM3bDNNSE9QU1M4Cm45azIydWd4MUxQdCs0VlpLVU14
            V0lHeGZNRDJwdy9ocG1mU1NaMDZqQ2MKLS0tIFNGTWlnaXNOc3lhM2dEemZTTVlR
            bzBNRGdrdU9MRDBMdGRVZ2VjY1FWOXMKv33yoSYozdo8CV50d7+iT5vNcSrj2gBJ
            uduaBj+B4lAnA1eKWWAw1nZigZGS5kf7lkKKvRjUjDIvReC10WBJAA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zt22uns634n9qxy34jjjp86cw5ruynpngge0ypdere8kq40ysylqh6ce5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RVBWbWR3dVEvd2E5Y3hy
            L1h3VUFiWXZMRExPNmttVGREaEdTZGpmV0VNCm8vT0VvWmkwblpXbWk4NGViZUwy
            WlVEZjBTRHZXd0g0QU8rRTIra3pUQ0UKLS0tIFlSK3JiSmNDU0M2WEJJeUR5Y21r
            WkVlOTNBVW1IaGdRUCtXT3luMDI2ZTAK1sjP9U3jWoopc3AHpwWJYL5+0cfzT/ge
            RQLzNCjcoO0eFSMPPn+k5MlCZ13F9Oyw85L45CEy4RsJ4NShXt/prw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-22T22:25:01Z"
    mac: ENC[AES256_GCM,data:KIoZ+FgVna7agPFSSsr5lc/0QhnWYEUlQaCeL+AHwjInFdjDxpoYVsJHxXG6ihukqQ7GfkhN5yIK/LwEet6BOV9/vioyZs8RKRKwo0sluabhmCTGP98FQo8x+q9lWWm1NPqGjvp4C+8yBoNyPtcPaLGEIsFjb3RNapQIcG4LLOs=,iv:GLKvJhgEK64jeWNX1IlBcp8mHz8fTI4ucW66ciddUbo=,tag:MOT5F52t/VtdhtPrCQ0LiQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
