---
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
radarr:
  streaming:
    base_url: http://radarr-movies.downloads.svc.cluster.local
    api_key: !env_var RADARR_MOVIES_API_KEY

    delete_old_custom_formats: true
    replace_existing_custom_formats: true

    quality_definition:
      type: sqp-streaming

    media_naming:
      folder: plex
      movie:
        rename: true
        standard: default

    quality_profiles:
      - &profile
        name: Streaming
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: true
          until_quality: Bluray|WEB-1080p
          until_score: 10000
        min_format_score: 1000
        score_set: sqp-1-1080p
        quality_sort: top
        qualities:
          - name: Bluray|WEB-1080p
            qualities:
            - Bluray-1080p
            - WEBDL-1080p
            - WEBRip-1080p
            - WEBDL-720p
            - WEBRip-720p
          - name: Bluray-720p

      - <<: *profile
        name: No Sync Streaming

    # Based off SQP-1
    custom_formats:
      - trash_ids:
          # Movie Versions
          - 570bc9ebecd92723d2d21500f4be314c  # Remaster
          - eca37840c13c6ef2dd0262b141a5482f  # 4K Remaster
          - e0c07d59beb37348e975a930d5e50319  # Criterion Collection
          - 9d27d9d2181838f76dee150882bdc58c  # Masters of Cinema
          - db9b4c4b53d312a3ca5f1378f6440fc9  # Vinegar Syndrome
          - 957d0f44b592285f26449575e8b1167e  # Special Edition

          # HQ Release Groups
          - 5153ec7413d9dae44e24275589b5e944  # BHDStudio
          - c20f169ef63c5f40c2def54abaf4438e  # WEB Tier 01
          - 403816d65392c79236dcb6dd591aeda4  # WEB Tier 02
          - af94e0fe497124d1f9ce732069ec8c3b  # WEB Tier 03
          - ed27ebfef2f323e964fb1f61391bcb35  # HD Bluray Tier 01
          - c20c8647f2746a1f4c4262b0fbbeeeae  # HD Bluray Tier 02
          - 5608c71bcebba0a5e666223bae8c9227  # HD Bluray Tier 03
        quality_profiles:
          - name: Streaming
          - name: No Sync Streaming