---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: irqbalance
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      irqbalance:
        type: daemonset

        pod:
          hostIPC: true
          hostPID: true

        containers:
          app:
            image:
              repository: ghcr.io/buroa/irqbalance
              tag: 1.9.4
            env:
              IRQBALANCE_BANNED_CPULIST: 12-15 # 12-15 are E-cores on Intel i7-12650H
            resources:
              requests:
                cpu: 25m
                memory: 128Mi
              limits:
                memory: 128Mi
            securityContext:
              privileged: true
