---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./replicationdestination.yaml
  # TODO: Ability to make backups disabled until all backups rehydrated successfully
  # - ./replicationsource.yaml
