---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: ${APP}-bootstrap
spec:
  trigger:
    manual: restore-once
  restic:
    repository: ${APP}-volsync-minio
    copyMethod: Snapshot
    accessModes: ["${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"]
    cacheAccessModes: ["${VOLSYNC_CACHE_ACCESSMODES:-ReadWriteOnce}"]
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:-1Gi}"
    cacheStorageClassName: ${VOLSYNC_CACHE_STORAGECLASS:-local-hostpath}
    capacity: "${VOLSYNC_CAPACITY:-1Gi}"
    storageClassName: "${VOLSYNC_STORAGECLASS:-ceph-block}"
    volumeSnapshotClassName: ${VOLSYNC_SNAPSHOTCLASS:-csi-ceph-blockpool}
    moverSecurityContext:
      runAsUser: ${APP_UID:-568}
      runAsGroup: ${APP_GID:-568}
      fsGroup: ${APP_GID:-568}
    enableFileDeletion: true
    cleanupCachePVC: true
    cleanupTempPVC: true
