---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: overseerr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: ghcr.io/engels74/overseerr-anime
              tag: release-1.33.2-anime@sha256:1bd9d65433e1314e5e079a6381d23731ec8cd18fc9e3e047ad91a70eb0e84288
            securityContext:
              privileged: true

    service:
      main:
        ports:
          http:
            port: 5055

    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.kyle.fail
        hosts:
          - host: &host1 requests.kyle.fail
            paths: &path
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
          - host: &host2 request.kyle.fail
            paths: *path
          - host: &host3 "{{ .Release.Name }}.kyle.fail"
            paths: *path
        tls:
          - hosts:
              - *host1
              - *host2
              - *host3

    persistence:
      config:
        enabled: true
        existingClaim: overseerr
        advancedMounts:
          main:
            main:
              - path: /app/config