---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: recyclarr-configmap
    files:
      - radarr-streaming.yml=./config/radarr-streaming.yml
      - radarr-hq.yml=./config/radarr-hq.yml
      - radarr-anime.yml=./config/radarr-anime.yml
      - sonarr-tv.yml=./config/sonarr-tv.yml
      - sonarr-anime.yml=./config/sonarr-anime.yml
generatorOptions:
  disableNameSuffixHash: true
