---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app external-dns-cloudflare
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app

    resources:
      requests:
        cpu: 13m
        memory: 42M
      limits:
        memory: 42M

    domainFilters:
      - kyle.fail

    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns-cloudflare-secret
            key: CLOUDFLARE_API_TOKEN

    extraArgs:
      - --cloudflare-proxied
      - --ingress-class=external

    policy: sync
    provider: cloudflare

    sources:
      - ingress

    txtOwnerId: default
    txtPrefix: k8s.

    serviceMonitor:
      enabled: true

    podAnnotations:
      secret.reloader.stakater.com/reload: external-dns-cloudflare-secret