---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APP}-minio
spec:
  sourcePVC: ${APP}
  trigger:
    schedule: 0 * * * * # At the top of every hour
  restic:
    copyMethod: ${VOLSYNC_COPYMETHOD:-Snapshot}
    repository: ${APP}-volsync-minio
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:-1Gi}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-csi-ceph-blockpool}"
    storageClassName: "${VOLSYNC_STORAGECLASS:-ceph-block}"
    cacheStorageClassName: "${VOLSYNC_CACHE_STORAGECLASS:-local-hostpath}"
    cacheAccessModes: ["${VOLSYNC_CACHE_ACCESSMODES:-ReadWriteOnce}"]
    accessModes: ["${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"]
    moverSecurityContext:
      runAsUser: ${APP_UID:-568}
      runAsGroup: ${APP_GID:-568}
      fsGroup: ${APP_GID:-568}
    pruneIntervalDays: 7
    retain: # keep 24 hourly, 7 daily, and 5 weekly backups
      hourly: 24
      daily: 7
      weekly: 5
