---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tachidesk
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: ${APP_UID}
            runAsGroup: ${APP_GID}
            fsGroup: ${APP_GID}
            runAsNonRoot: true
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups: [44, 105, 10000]

        containers:
          main:
            image:
              repository: ghcr.io/suwayomi/tachidesk
              tag: v1.1.1@sha256:2ab0107a86970367a80346d5ea645bce7997896272d75cff1d0bd866c78f34b5
            env:
              BIND_PORT: &port 80
              EXTENSION_REPOS: "[\"https://github.com/keiyoushi/extensions/tree/repo\"]"
              FLARESOLVERR_ENABLED: false
              FLARESOLVERR_URL: http://flaresolverr.downloads.svc.cluster.local
              UPDATE_EXCLUDE_STARTED: false
              UPDATE_EXCLUDE_UNREAD: false
              WEB_UI_CHANNEL: "preview"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /manifest.json
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              limits:
                memory: 4Gi
              requests:
                cpu: 25m

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        className: internal
        hosts:
          - host: &host "{{ .Release.Name }}.kyle.fail"
            paths:
              - path: /
                service:
                  name: main
                  port: *port
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: tachidesk
        globalMounts:
          - path: /home/suwayomi/.local/share/Tachidesk
      downloads:
        enabled: true
        type: nfs
        server: tank.kyle.fail
        path: /mnt/tank/media
        globalMounts:
          - path: /home/suwayomi/.local/share/Tachidesk/downloads
            subPath: downloads/tachidesk
      tmp:
        type: emptyDir