---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr-anime
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: radarr-anime-secret
    template:
      engineVersion: v2
      data:
        RADARR__API_KEY: "{{ .RADARR_ANIME_API_KEY }}"
        RADARR__POSTGRES_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        RADARR__POSTGRES_PORT: "5432"
        RADARR__POSTGRES_USER: &dbUser "{{ .RADARR_ANIME_POSTGRES_USER }}"
        RADARR__POSTGRES_PASSWORD: &dbPass "{{ .RADARR_ANIME_POSTGRES_PASSWORD }}"
        RADARR__POSTGRES_MAIN_DB: radarr_anime_main
        RADARR__POSTGRES_LOG_DB: radarr_anime_log
        INIT_POSTGRES_DBNAME: radarr_anime_main radarr_anime_log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: radarr