---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kometa
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kometa-secret
    template:
      engineVersion: v2
      data:
        KOMETA_TMDB_API_KEY: "{{ .TMDB_API_KEY }}"
        KOMETA_PLEX_API_KEY: "{{ .PLEX_TOKEN }}"
  dataFrom:
    - extract:
        key: tmdb
    - extract:
        key: plex