---
version: "3"

includes:
  main:
    taskfile: ../../kubernetes/main

tasks:
  cluster-switch:
    aliases: [ctx]
    desc: Switch kubeconfig current-context to another cluster
    requires:
      vars: [cluster]
    cmd: "sed -i 's/current-context: admin@.*/current-context: admin@{{.cluster}}/g' ~/.kube/config || true"

  new-ns:
    aliases: [ns]
    desc: Create a new namespace from a tempalte
    requires:
      vars: [cluster, ns]
    silent: true
    cmds:
      - cp -r /{{.ROOT_DIR}}/.task/cluster/templates/namespace /{{.ROOT_DIR}}/kubernetes/{{.cluster}}/apps/{{.ns}}/
      - grep -lR 'NAMESPACE' /{{.ROOT_DIR}}/kubernetes/{{.cluster}}/apps/{{.ns}}/ | xargs -I% sed -i 's/${NAMESPACE}/{{.ns}}/g' %

  new-app:
    aliases: [app]
    desc: Create a new app from template
    requires:
      vars: [cluster, ns, app]
    silent: true
    cmds:
      - cp -r /{{.ROOT_DIR}}/.task/cluster/templates/app /{{.ROOT_DIR}}/kubernetes/{{.cluster}}/apps/{{.ns}}/{{.app}}/
      - grep -lR 'APP' /{{.ROOT_DIR}}/kubernetes/{{.cluster}}/apps/{{.ns}}/{{.app}}/ | xargs -I% sed -i 's/${APP}/{{.app}}/g' %
      - grep -lR 'NAMESPACE' /{{.ROOT_DIR}}/kubernetes/{{.cluster}}/apps/{{.ns}}/{{.app}}/ | xargs -I% sed -i 's/${NAMESPACE}/{{.ns}}/g' %

  delete-failed-pods:
    desc: Deletes pods with Failed phase
    cmd: kubectl delete pods --field-selector status.phase=Failed -A --ignore-not-found=true

  delete-succeeded-pods:
    desc: Deletes pods with Succeeded phase
    cmd: kubectl delete pods --field-selector status.phase=Succeeded -A --ignore-not-found=true