---
version: "3"

includes:
  main:
    taskfile: ../../kubernetes/main

tasks:
  delete-failed-pods:
    desc: Deletes pods with Failed phase
    cmd: kubectl delete pods --field-selector status.phase=Failed -A --ignore-not-found=true

  delete-succeeded-pods:
    desc: Deletes pods with Succeeded phase
    cmd: kubectl delete pods --field-selector status.phase=Succeeded -A --ignore-not-found=true