---
version: "3"

includes:
  main:
    taskfile: ../../kubernetes/main

tasks:
  watch:
    desc: Watches a namespace to monitor for changes
    requires:
      vars: [ns]
    cmd: viddy -n1 kubectl get all -n {{.ns}}

  delete-failed-pods:
    desc: Deletes pods with Failed phase
    cmd: kubectl delete pods --field-selector status.phase=Failed -A --ignore-not-found=true

  delete-succeeded-pods:
    desc: Deletes pods with Succeeded phase
    cmd: kubectl delete pods --field-selector status.phase=Succeeded -A --ignore-not-found=true

  cleanup:
    desc: Dletes pods with Failed and Succeeded phase
    cmds:
      - task: delete-failed-pods
      - task: delete-succeeded-pods