---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kavita
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      kavita:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/kareadita/kavita
              tag: 0.8.5@sha256:0266bd9cfedfcb36c72b43a43257c9d1049ab7da58acd9f90130d288deb1ac0a
            resources:
              requests:
                cpu: 15m
                memory: 300Mi
              limits:
                memory: 4Gi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [44, 105, 10000]

    service:
      app:
        controller: *app
        ports:
          http:
            port: 5000

    ingress:
      app:
        className: internal
        hosts:
          - host: "{{ .Release.Name }}.kyle.fail"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        existingClaim: kavita
        globalMounts:
          - path: /kavita/config
      media:
        type: nfs
        server: virtual-nas.internal
        path: /mnt/tank/media
        globalMounts:
          - path: /media
            readOnly: true
