---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: alertmanager
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"

        statefulset:
          volumeClaimTemplates:
            - name: storage
              accessMode: ReadWriteOnce
              size: 50Mi
              storageClass: ceph-block
              globalMounts:
                - path: /alertmanager

        containers:
          main:
            image:
              repository: quay.io/prometheus/alertmanager
              tag: v0.27.0
            ports:
              - name: http
                containerPort: 9093
            resources:
              requests:
                cpu: 11m
                memory: 50M
              limits:
                memory: 99M
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch

    service:
      main:
        ports:
          http:
            port: 9093

    ingress:
      main:
        enabled: true
        className: internal
        hosts:
          - host: &host alertmanager.kyle.fail
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      secrets:
        type: secret
        name: alertmanager-secret
        globalMounts:
          - path: /etc/alertmanager