---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app external-dns-bind-crds
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.13.1
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app

    resources:
      requests:
        cpu: 13m
        memory: 42M
      limits:
        memory: 42M

    domainFilters:
      - kyle.fail

    policy: sync
    provider: rfc2136

    env:
      - name: EXTERNAL_DNS_RFC2136_HOST
        value: "192.168.2.58"
      - name: EXTERNAL_DNS_RFC2136_PORT
        value: "53"
      - name: EXTERNAL_DNS_RFC2136_ZONE
        value: kyle.fail
      - name: EXTERNAL_DNS_RFC2136_TSIG_AXFR
        value: "true"
      - name: EXTERNAL_DNS_RFC2136_TSIG_KEYNAME
        value: externaldns-key
      - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET_ALG
        value: hmac-sha256
      - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
        valueFrom:
          secretKeyRef:
            name: external-dns-bind-secret
            key: BIND_RNDC_KEY

    extraArgs:
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --label-filter="target-dns==internal"

    sources:
      - crd

    txtOwnerId: default
    txtPrefix: k8s.

    podAnnotations:
      secret.reloader.stakater.com/reload: external-dns-bind-secret