apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloudflare-secret
data:
    CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:Fb6fXNlUYXHlwdySOMClll0pUIk3htM9udIUsNVLodOd1W4EfwPWRyFQDb8extgV1z5x6ABZUjA=,iv:JZk4AssVMekXszXuKxIIYPGb4xKPndqPN27aIg+MAw8=,tag:uAq5XnoPafVTb+98RyqTWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rss899lzcafjv5y8ve8cj4urhqfyypwrlqua2jmeyusmkdmugdxqsluwyl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZGZRK2JwUWtrQWpCRlBy
            VkpJa1JPaUZQSHdBZWVjdE5vc09ZVTRPdzNvCitJdG5icm9ySFhnVVB5Rkk0aTFx
            SE4wbXArTTVremZmdkxjUTdYMEF3UUUKLS0tIGJlV0V0aTZGeWhuOXdQd21aMzVO
            ayttc0ptbUtKenkrL0IvUlNJMGtLUmsKobPvLR5ozT9Wqr6TfnY/Ym4TNkN89G5J
            bzCMcj3BnULEqf/lw6ZNAPOrlWdv5amrmxfebnEePXdmjiTyqSCGfQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zt22uns634n9qxy34jjjp86cw5ruynpngge0ypdere8kq40ysylqh6ce5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMVEzS0dKTUhab3pYNGhJ
            QkI3UU00SkhJMXAvekw5LzkvTmdwTXg5RVFjCjVJUFJXS1NwNlZWMHZPVXNBbHRY
            SEpnSlp0U1p1WXg2VExwMkQ5NWpoS00KLS0tIGFDNmlMZVhWL0x1L2tsc0l3WTRI
            Tkcxb25QanpsK1RvNVdrVzZiem5iTWsKQt0ifJ/rQZyh8LGK1tdeVmVdTG1RVMGy
            UcyPwYV4VgqfhkoYqBfX+3ttLRLw+/yUl4YGj5Hhy95+OSL3655XTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-31T08:27:44Z"
    mac: ENC[AES256_GCM,data:W78n2MhylWlU1PqMlv9IMMlIgvKvKHB3nG+8swPPSKqiTAwRT8uHjwDawx5LbENxAv91KAqPYvbS4HquM4tmRxVcCUKBpo4HurYSJGlu/Ty51VrTsahuy1tvg9OnkQEQ9/ewH3mG9Hp7vQBeAYgq2bLFmTxp/7UIMIWhnQD3fD4=,iv:oYJAR/2SrZuQPGBSptoUQA9HvVe2pFmVLGiNT4SWAo8=,tag:IJG3Q9+rcnrcL+XdagfOSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
