---
version: "3"

includes:
  k8s:
    internal: true
    taskfile: ../k8s

vars:
  cluster: '{{ .cluster | default "main" }}'

tasks:
  desc: Runs talosctl with a generated talosconfig
  default:
    vars:
      cluster: &cluster '{{ or .cluster (fail "Argument (cluster) is required") }}'
      talosconfig: /{{.ROOT_DIR}}/kubernetes/{{.cluster}}/talos/clusterconfig/talosconfig
    cmd: talosctl {{.CLI_ARGS}} --talosconfig {{.talosconfig}}

  health:
    desc: Gets the current health status of the cluster
    summary: |
      Args:
        cluster: cluster to run command against (required)
        ip:      address of node to apply (required)
    vars:
      cluster: *cluster
      ip: '{{ or .ip (fail "Argument (ip) is required") }}'
      talosconfig: /{{.ROOT_DIR}}/kubernetes/{{.cluster}}/talos/clusterconfig/talosconfig
    cmd: talosctl health --nodes {{.ip}} --talosconfig {{.talosconfig}}

  genconfig:
    aliases: [gen]
    desc: Generate talos configs from talhelper
    dir: &dir "/{{.ROOT_DIR}}/kubernetes/{{.cluster}}/talos"
    summary: |
      Args:
        cluster: Cluster to run command against (required)
    vars:
      cluster: *cluster
    cmds:
      - talhelper genconfig
    sources:
      - /{{.ROOT_DIR}}/kubernetes/{{.cluster}}/talos/talconfig.yaml
      - /{{.ROOT_DIR}}/kubernetes/{{.cluster}}/talos/talenv.sops.yaml
      - /{{.ROOT_DIR}}/kubernetes/{{.cluster}}/talos/talsecret.sops.yaml
    generates:
      - /{{.ROOT_DIR}}/kubernetes/{{.cluster}}/talos/clusterconfig/*

  apply:
    dir: *dir
    desc: Apply talos config to a given node
    vars: &apply-vars
      node: '{{ or .node (fail "Argument (node) is required") }}'
      ip: '{{ .ip | default .node }}'
      cluster: *cluster
    summary: &apply-summary |
      Args:
        cluster: Cluster to run command against (required)
        node:    name of the node to use (required)
        ip:      address of node to apply (node name if not specified)
    cmds:
      - task: genconfig
      - |-
        talosctl apply-config \
            --nodes {{.ip}} \
            --file /{{.ROOT_DIR}}/kubernetes/{{.cluster}}/talos/clusterconfig/{{.cluster}}-{{.node}}.yaml \
            --talosconfig /{{.ROOT_DIR}}/kubernetes/{{.cluster}}/talos/clusterconfig/talosconfig \
            {{.CLI_ARGS}}

  init:
    desc: Apply initial talos config to a given node (insecure)
    dir: *dir
    summary: *apply-summary
    vars: *apply-vars
    cmd:
      task: apply
      vars: {cluster: "{{.cluster}}", node: "{{.node}}", ip: "{{.ip}}", CLI_ARGS: "--insecure"}

  bootstrap:
    desc: Run all bootstrap related tasks for a talos cluster
    dir: *dir
    summary: |
      Args:
        cluster:  cluster to run command against (required)
        ip:       address of node to bootstrap (required)
    vars:
      cluster: *cluster
      ip: '{{ or .ip (fail "Argument (ip) is required") }}'
      talosconfig: /{{.ROOT_DIR}}/kubernetes/{{.cluster}}/talos/clusterconfig/talosconfig
    cmds:
      - until talosctl bootstrap --talosconfig {{.talosconfig}} --nodes {{.ip}} ; do sleep 1; done
      - until talosctl kubeconfig --talosconfig {{.talosconfig}} --nodes {{.ip}} ; do sleep 1; done
      - "sed -i 's/current-context: admin@.*/current-context: admin@{{.cluster}}/g' ~/.kube/config || true"

  reset:
    desc: Reset a node, wiping its STATE and EPHEMERAL partitions
    dir: *dir
    summary: |
      Args:
        cluster:  cluster to run command against (required)
        ip:       address of node to reset (required)
        graceful: attempt to drain the node (default true)
    vars:
      cluster: *cluster
      ip: '{{ or .ip (fail "Argument (ip) is required") }}'
      graceful: '{{ .graceful | default "true" }}'
    prompt: This will destroy the target node and reset to a default talos install... Continue?
    cmd:
      task: reset-no-prompt

  # useful for other reset scripts
  reset-no-prompt:
    internal: true
    vars:
      cluster: *cluster
      ip: '{{ or .ip (fail "Argument (ip) is required") }}'
      graceful: '{{ .graceful | default "true" }}'
    cmd: |-
      talosctl reset \
          --system-labels-to-wipe STATE --system-labels-to-wipe EPHEMERAL \
          --graceful={{.graceful}} --reboot=true \
          --talosconfig /{{.ROOT_DIR}}/kubernetes/{{.cluster}}/talos/clusterconfig/talosconfig \
          --nodes {{.ip}}