---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  # Flux Kustomizations
  - ./snapshot-controller/ks.yaml
  # - ./democratic-csi/ks.yaml
  - ./volsync/ks.yaml