---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  # Flux Kustomizations
  - ./qbittorrent/ks.yaml
  - ./prowlarr/ks.yaml
  - ./autobrr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./cross-seed/ks.yaml
  - ./filebrowser/ks.yaml
  - ./tranga/ks.yaml