---
route:
  group_by: ["alertname", "job"]
  group_interval: 5m
  group_wait: 30s
  receiver: discord
  repeat_interval: 6h
  routes:
    - receiver: "null"
      matchers:
        - alertname =~ "InfoInhibitor|Watchdog"
    - receiver: discord
      continue: true
      matchers:
        - severity = "critical"
inhibit_rules:
  - equal: ["alertname", "namespace"]
    source_matchers:
      - severity = "critical"
    target_matchers:
      - severity = "warning"
receivers:
  - name: "null"
  - name: discord
    discord_configs:
      - send_resolved: true
        webhook_url: "{{ .DISCORD_URL }}"
        title: >-
          {{ "{{" }} .CommonLabels.alertname {{ "}}" }}
          [{{ "{{" }} .Status | toUpper {{ "}}" }}{{ "{{" }} if eq .Status "firing" {{ "}}" }}:{{ "{{" }} .Alerts.Firing | len {{ "}}" }}{{ "{{" }} end {{ "}}" }}]
        message: |-
          {{ "{{-" }} range .Alerts {{ "}}" }}
            {{ "{{-" }} if ne .Annotations.description "" {{ "}}" }}
              {{ "{{" }} .Annotations.description {{ "}}" }}
            {{ "{{-" }} else if ne .Annotations.summary "" {{ "}}" }}
              {{ "{{" }} .Annotations.summary {{ "}}" }}
            {{ "{{-" }} else if ne .Annotations.message "" {{ "}}" }}
              {{ "{{" }} .Annotations.message {{ "}}" }}
            {{ "{{-" }} else {{ "}}" }}
              Alert description not available
            {{ "{{-" }} end {{ "}}" }}
            {{ "{{-" }} if gt (len .Labels.SortedPairs) 0 {{ "}}" }}
              {{ "{{-" }} range .Labels.SortedPairs {{ "}}" }}
                **{{ "{{" }} .Name {{ "}}" }}:** {{ "{{" }} .Value {{ "}}" }}
              {{ "{{-" }} end {{ "}}" }}
            {{ "{{-" }} end {{ "}}" }}
          {{ "{{-" }} end {{ "}}" }}