---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cross-seed
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          secret.reloader.stakater.com/reload: cross-seed-secret

        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 10000

        containers:
          main:
            image:
              repository: ghcr.io/cross-seed/cross-seed
              tag: 5.9.2@sha256:6abdca45f0ecfd8d23a3035beefa716a14b66f23c14854631fe369d1ad346f1e
            args: [daemon]
            env:
              CROSSSEED_PORT: &port 80
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 256Mi

    service:
      main:
        ports:
          http:
            port: *port

    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent
        globalMounts:
          - path: /config
      config-file:
        type: secret
        name: cross-seed-secret
        globalMounts:
          - path: /config/config.js
            subPath: config.js
            readOnly: true
      media:
        type: nfs
        server: tank.kyle.fail
        path: /mnt/tank/media
        globalMounts:
          - path: /media