---
version: "3"

includes:
  k8s:
    internal: true
    taskfile: ../../.task/k8s
    aliases: [k8s]
  talos:
    internal: true
    taskfile: ../../.task/talos
    aliases: [talos]

vars:
  cluster: main

tasks:
  apply-all:
    desc: Apply the talos config to all nodes
    cmds:
      - task: talos:genconfig
      - task: talos:apply
        vars: { node: augustus, ip: 192.168.10.20 }
      - task: talos:apply
        vars: { node: nero, ip: 192.168.10.21 }
      - task: talos:apply
        vars: { node: titus, ip: 192.168.10.22 }

  bootstrap:
    desc: Bootstrap the cluster
    vars:
      ip: '{{ .ip | default "192.168.10.20" }}'
    cmds:
      - task: apply-all
      - task: talos:bootstrap
        vars: { ip: "{{.ip}}" }
      - task: k8s:cilium-bootstrap-apply
      - task: k8s:csr-bootstrap-apply
      # TODO: bootstrap flux
      - task: talos:health
        vars: { ip: "{{.ip}}" }

  reset:
    desc: Reset the cluster back to default talos installation
    prompt: This will destroy the cluster and reset to a default talos install... Continue?
    cmds:
      - task: talos:reset-no-prompt
        vars: { ip: 192.168.10.20, graceful: "false" }
      - task: talos:reset-no-prompt
        vars: { ip: 192.168.10.21, graceful: "false" }
      - task: talos:reset-no-prompt
        vars: { ip: 192.168.10.22, graceful: "false" }