---
version: "3"

tasks:
  cilium-bootstrap-apply:
    internal: true
    desc: Bootstrap Cilium onto a new cluster
    vars:
      cluster: '{{ or .cluster (fail "Argument (cluster) is required") }}'
    cmds:
      - kubectl delete configmap -n kube-system cilium-config || true
      - kubectl delete daemonset -n kube-system cilium || true
      - kubectl delete deployment -n kube-system cilium-operator hubble-ui hubble-relay || true
      - cmd: kustomize build --enable-helm /{{.ROOT_DIR}}/kubernetes/{{.cluster}}/bootstrap/cilium/ | envsubst | kubectl delete -f -
        ignore_error: true
      - kustomize build --enable-helm /{{.ROOT_DIR}}/kubernetes/{{.cluster}}/bootstrap/cilium/ | envsubst | kubectl apply -f -
    preconditions:
      - test -f /{{.ROOT_DIR}}/kubernetes/{{.cluster}}/bootstrap/cilium/kustomization.yaml

  csr-bootstrap-apply:
    internal: true
    desc: Bootstrap kubelet-csr-approver
    vars:
      cluster: '{{ or .cluster (fail "Argument (cluster) is required") }}'
    cmds:
      - cmd: kustomize build --enable-helm /{{.ROOT_DIR}}/kubernetes/{{.cluster}}/bootstrap/kubelet-csr-approver/ | envsubst | kubectl delete -f -
        ignore_error: true
      - kustomize build --enable-helm /{{.ROOT_DIR}}/kubernetes/{{.cluster}}/bootstrap/kubelet-csr-approver/ | envsubst | kubectl apply -f -
    preconditions:
      - test -f /{{.ROOT_DIR}}/kubernetes/{{.cluster}}/bootstrap/kubelet-csr-approver/kustomization.yaml