---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: silence-operator-crds
spec:
  interval: 1h
  chart:
    spec:
      chart: silence-operator-crds
      version: 0.0.3
      sourceRef:
        kind: HelmRepository
        name: wiremind
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
