---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: democratic-csi-local-path
spec:
  interval: 30m
  chart:
    spec:
      chart: democratic-csi
      version: 0.14.3
      sourceRef:
        name: democratic-csi
        kind: HelmRepository
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    podAnnotations:
      reloader.stakater.com/auto: "true"

    controller:
      strategy: node
      externalProvisioner:
        image: registry.k8s.io/sig-storage/csi-provisioner:v3.6.4
        extraArgs:
          - --leader-election=false
          - --node-deployment=true
          - --node-deployment-immediate-binding=false
          - --feature-gates=Topology=true
          - --strict-topology=true
          - --enable-capacity=true
          - --capacity-ownerref-level=1
      externalResizer:
        enabled: false
      externalAttacher:
        enabled: false
      externalSnapshotter:
        enabled: true
        extraArgs:
          - --leader-election=false
          - --node-deployment=true

    csiDriver:
      name: local-hostpath.democratic-csi.main.cluster.local
      attachRequired: false
      storageCapacity: true # With storage capacity tracking, the scheduler filters out nodes which do not have enough capacity.
      fsGroupPolicy: File # fsGroupChangePolicy

    storageClasses:
      - name: local-hostpath
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: WaitForFirstConsumer
        allowVolumeExpansion: true

    volumeSnapshotClasses:
      - name: local-hostpath
        deletionPolicy: Delete
        parameters:
          dummy: {}

    driver:
      config:
        driver: local-hostpath
        local-hostpath:
          shareBasePath: &storagePath /var/lib/democratic-csi-local-hostpath
          controllerBasePath: *storagePath
          dirPermissionsMode: "0770"
          dirPermissionsUser: 0
          dirPermissionsGroup: 0

    node:
      driver:
        image: ghcr.io/democratic-csi/democratic-csi:v1.8.4
        driverRegistrar:
          enabled: true
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.9.3
        extraVolumeMounts:
          - name: local-hostpath
            mountPath: *storagePath
            mountPropagation: Bidirectional
      extraVolumes:
        - name: local-hostpath
          hostPath:
            path: *storagePath
            type: DirectoryOrCreate