---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tranga
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: glax/tranga-website
              tag: latest@sha256:c2ebd706dc4c4d9859de27739fbb6229b5ea0dee261789dfc22bc5a44ce23f55
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 25m
              limits:
                memory: 512Mi
          api:
            image:
              repository: glax/tranga-api
              tag: latest@sha256:b156a04092827082065ec62e206c09157d864af834ed43f78170c43cbb392c51
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /Ping
                    port: &portApi 6531
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 30m
              limits:
                memory: 4Gi

    service:
      main:
        ports:
          http:
            primary: true
            port: &portWeb 80
          api:
            port: *portApi

    ingress:
      main:
        enabled: true
        className: internal
        hosts:
          - host: &host "{{ .Release.Name }}.kyle.fail"
            paths:
              - path: /
                service:
                  name: main
                  port: *portWeb
          - host: &hostApi "{{ .Release.Name }}-api.kyle.fail"
            paths:
              - path: /
                service:
                  name: main
                  port: *portApi
        tls:
          - hosts:
              - *host
              - *hostApi

    persistence:
      config:
        enabled: true
        # existingClaim: tranga
        type: emptyDir
        globalMounts:
          - path: /usr/share/tranga-api
      manga:
        enabled: true
        type: nfs
        server: tank.kyle.fail
        path: /mnt/tank/media
        globalMounts:
          - path: /Manga
            subPath: downloads/tranga
      tmp:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /var/cache/nginx