---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tranga
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: glax/tranga-api
              tag: latest@sha256:207960b71d0ad41110ae9ce74cf7966620ff7a96083b518a881ee03c5005edfe
            # probes:
            #   liveness: &probes
            #     enabled: true
            #     custom: true
            #     spec:
            #       httpGet:
            #         path: /Ping
            #         port: 6531
            #       initialDelaySeconds: 0
            #       periodSeconds: 10
            #       timeoutSeconds: 1
            #       failureThreshold: 3
            #   readiness: *probes
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 30m
              limits:
                memory: 4Gi
          web:
            image:
              repository: glax/tranga-website
              tag: latest@sha256:93db8d40292e1298f0c2bddaae3f4566c2b69ca5fd488a245cc45262833d923a
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 25m
              limits:
                memory: 512Mi

    service:
      web:
        ports:
          http:
            port: &port 9555

    ingress:
      web:
        enabled: true
        className: internal
        hosts:
          - host: &host "{{ .Release.Name }}.kyle.fail"
            paths:
              - path: /
                service:
                  name: web
                  port: *port
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        # existingClaim: tranga
        type: emptyDir
        globalMounts:
          - path: /usr/share/tranga-api
      manga:
        enabled: true
        type: nfs
        server: tank.kyle.fail
        path: /mnt/tank/media
        globalMounts:
          - path: /Manga
            subPath: downloads/tranga
      tmp:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /var/cache/nginx