---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  # Flux Kustomizations
  - ./cloudflared/ks.yaml
  - ./nginx/ks.yaml
  - ./external-dns/ks.yaml
  - ./echo-server/ks.yaml
  - ./external-services/ks.yaml