---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kube-prometheus-stack
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kube-prometheus-stack-secret
    template:
      engineVersion: v2
      data:
        objstore.yml: |-
          type: s3
          config:
            bucket: thanos
            endpoint: s3.kyle.fail
            access_key: {{ .MINIO_ACCESS_KEY_ID }}
            secret_key: {{ .MINIO_SECRET_ACCESS_KEY }}
  dataFrom:
    - extract:
        key: thanos