---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: upgradinatorr
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: upgradinatorr-secret
    template:
      data:
        config.yml: |
          main:
            log_level: debug
          schedule: {}
          instances:
            radarr:
              radarr_anime:
                url: http://radarr-anime.downloads.svc.cluster.local
                api: "{{.RADARR_ANIME_API_KEY}}"
              hd:
                url: http://radarr-hd.downloads.svc.cluster.local
                api: "{{.RADARR_MOVIES_API_KEY}}"
              uhd:
                url: http://radarr-uhd.downloads.svc.cluster.local
                api: "{{.RADARR_HQ_API_KEY}}"
            sonarr:
              sonarr_anime:
                url: http://sonarr-anime.downloads.svc.cluster.local
                api: "{{.SONARR_ANIME_API_KEY}}"
              tv:
                url: http://sonarr-tv.downloads.svc.cluster.local
                api: "{{.SONARR_TV_API_KEY}}"
          discord:
            upgradinatorr:
              discord_webhook: "{{.DAPS_UPGRADINATORR_WEBHOOK}}"
          upgradinator:
            log_level: debug
            dry_run: true
            instances:
              hd:
                count: 10
                tag_name: upgradinator
                ignore_tag: ignore-upgrade
                unattended: true
  dataFrom:
    - extract:
        key: sonarr
    - extract:
        key: radarr
    - extract:
        key: daps
