---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr-uhd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: radarr-uhd-secret
    template:
      data:
        RADARR__AUTH__APIKEY: "{{ .RADARR_HQ_API_KEY }}"
  dataFrom:
    - extract:
        key: radarr
