---
# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json

clusterName: &cluster main
endpoint: https://192.168.1.100:6443

# renovate: depName=ghcr.io/siderolabs/installer datasource=docker
talosVersion: v1.9.4
# renovate: depName=ghcr.io/siderolabs/kubelet datasource=docker
kubernetesVersion: v1.32.2

additionalApiServerCertSans: &sans
  - &clusterVIP 192.168.1.100
  - 127.0.0.1 #KubePrism
additionalMachineCertSans: *sans

cniConfig:
  name: none

nodes:
  # GEEKOM IT12, i7-12650H w/ Sonnet 10G thunderbolt -> SFP+
  - hostname: augustus
    ipAddress: 192.168.1.14
    controlPlane: true
    installDiskSelector:
      model: CT500MX500SSD1
    networkInterfaces:
      # AQtion AQC100S NBase-T/IEEE 802.3an Ethernet Controller [Atlantic 10G]
      - deviceSelector:
          hardwareAddr: 00:30:93:12:*
        dhcp: true
        mtu: 9000
        vip:
          ip: *clusterVIP

  # GEEKOM IT12, i7-12650H w/ Sonnet 10G thunderbolt -> SFP+
  - hostname: nero
    ipAddress: 192.168.1.15
    controlPlane: true
    installDiskSelector:
      model: CT500MX500SSD1
    networkInterfaces:
      # AQtion AQC100S NBase-T/IEEE 802.3an Ethernet Controller [Atlantic 10G]
      - deviceSelector:
          hardwareAddr: 00:30:93:12:*
        dhcp: true
        mtu: 9000
        vip:
          ip: *clusterVIP

  # GEEKOM IT12, i7-12650H w/ Sonnet 10G thunderbolt -> SFP+
  - hostname: titus
    ipAddress: 192.168.1.16
    controlPlane: true
    installDiskSelector:
      model: CT500MX500SSD1
    networkInterfaces:
      # AQtion AQC100S NBase-T/IEEE 802.3an Ethernet Controller [Atlantic 10G]
      - deviceSelector:
          hardwareAddr: 00:30:93:12:*
        dhcp: true
        mtu: 9000
        vip:
          ip: *clusterVIP

# Cluster wide patches
patches:
  # Configure containerd
  - |
    machine:
      files:
        - # Spegel
          op: create
          path: /etc/cri/conf.d/20-customization.part
          content: |
            [plugins."io.containerd.cri.v1.images"]
              discard_unpacked_layers = false

  # Disable search domain everywhere
  - |-
    machine:
      network:
        disableSearchDomain: true

  # Mount openebs-hostpath in kubelet
  - |-
    machine:
      kubelet:
        extraMounts:
          - destination: /var/openebs/local
            type: bind
            source: /var/openebs/local
            options: ["bind", "rshared", "rw"]

  # Configure kubelet
  - |-
    machine:
      kubelet:
        extraConfig:
          maxPods: 150
        nodeIP:
          validSubnets:
              - 192.168.1.0/24

  # Enable MutatingAdmissionPolicy
  - |-
    cluster:
      apiServer:
        extraArgs:
          enable-aggregator-routing: true
          feature-gates: MutatingAdmissionPolicy=true
          runtime-config: admissionregistration.k8s.io/v1alpha1=true

  # Configure NFS mount options
  - |
    machine:
      files:
        - op: overwrite
          path: /etc/nfsmount.conf
          permissions: 0o644
          content: |
            [ NFSMount_Global_Options ]
            nfsvers=4.2
            hard=True
            noatime=True
            nconnect=16

  # Custom sysctl settings
  - |-
    machine:
      sysctls:
        fs.inotify.max_user_watches: 1048576   # Watchdog
        fs.inotify.max_user_instances: 8192    # Watchdog
        net.core.default_qdisc: fq             # 10Gb/s
        net.core.rmem_max: 67108864            # 10Gb/s | Cloudflared / QUIC
        net.core.wmem_max: 67108864            # 10Gb/s | Cloudflared / QUIC
        net.ipv4.tcp_congestion_control: bbr   # 10Gb/s
        net.ipv4.tcp_fastopen: 3               # Send and accept data in the opening SYN packet
        net.ipv4.tcp_mtu_probing: 1            # 10Gb/s | Jumbo frames
        net.ipv4.tcp_rmem: 4096 87380 33554432 # 10Gb/s
        net.ipv4.tcp_wmem: 4096 65536 33554432 # 10Gb/s
        net.ipv4.tcp_window_scaling: 1         # 10Gb/s
        vm.nr_hugepages: "1024"                # PostgreSQL

# Control node specific configurations
controlPlane:
  nodeLabels:
    topology.kubernetes.io/region: *cluster
    topology.kubernetes.io/zone: IT12

  schematic:
    customization:
      extraKernelArgs:
        - i915.enable_guc=3                   # Alder Lake CPU / iGPU
        - sysctl.kernel.kexec_load_disabled=1 # Alder Lake CPU / iGPU
        - apparmor=0                          # Less security, more speed
        - init_on_alloc=0                     # Less security, more speed
        - init_on_free=0                      # Less security, more speed
        - mitigations=off                     # Less security, more speed
        - security=none                       # Less security, more speed
        - talos.auditd.disabled=1             # Less security, more speed
        - intel_iommu=on                      # PCI Passthrough
        - iommu=pt                            # PCI Passthrough
        - net.ifnames=1                       # Enable predictable NIC naming
        # - module_blacklist=igc                # Disable onboard NIC
      systemExtensions:
        officialExtensions:
          - siderolabs/i915
          - siderolabs/intel-ucode
          - siderolabs/thunderbolt

  patches:
    # Cluster configuration
    - |-
      cluster:
        allowSchedulingOnControlPlanes: true
        controllerManager:
          extraArgs:
            bind-address: 0.0.0.0
        coreDNS:
          disabled: true
        proxy:
          disabled: true
        scheduler:
          extraArgs:
            bind-address: 0.0.0.0
          config:
            apiVersion: kubescheduler.config.k8s.io/v1
            kind: KubeSchedulerConfiguration
            profiles:
              - schedulerName: default-scheduler
                plugins:
                  score:
                    disabled:
                      - name: ImageLocality
                pluginConfig:
                  - name: PodTopologySpread
                    args:
                      defaultingType: List
                      defaultConstraints:
                        - maxSkew: 1
                          topologyKey: kubernetes.io/hostname
                          whenUnsatisfiable: ScheduleAnyway

    # Configure etcd
    - |-
      cluster:
        etcd:
          advertisedSubnets:
            - 192.168.1.0/24

    # Enable host dns
    - |-
      machine:
        features:
          hostDNS:
            enabled: true
            resolveMemberNames: true
            forwardKubeDNSToHost: false

    # Configure udev rules
    - |-
      machine:
        udev:
          rules:
            # Intel GPU
            - SUBSYSTEM=="drm", KERNEL=="renderD*", GROUP="44", MODE="0660"
            # Thunderbolt
            - ACTION=="add", SUBSYSTEM=="thunderbolt", ATTR{authorized}=="0", ATTR{authorized}="1"

    # Custom sysfs settings
    - |-
      machine:
        sysfs:
          devices.system.cpu.intel_pstate.hwp_dynamic_boost: 1
          devices.system.cpu.cpu0.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu1.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu2.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu3.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu4.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu5.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu6.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu7.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu8.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu9.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu10.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu11.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu12.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu13.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu14.cpufreq.energy_performance_preference: balance_performance
          devices.system.cpu.cpu15.cpufreq.energy_performance_preference: balance_performance

    # Disable default API server admission plugins.
    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl

    # Enable K8s Talos API Access
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
              - os:admin
            allowedKubernetesNamespaces:
              - system-upgrade
