apiVersion: v1
kind: Secret
metadata:
    name: external-dns-bind-secret
data:
    EXTERNAL_DNS_RFC2136_TSIG_SECRET: ENC[AES256_GCM,data:NRoqWdzSd7RRTafVpIXYtPH/lyPfnqVaF8HEhi1XMJu9piArLT0THj/SeB5nKqM1kZ3YkbIMIcCbfumK,iv:UPB0l+hFjDXDG+h8YDUYzk9YjUiz+SL3p5E2lVyWv44=,tag:jrsPfXLxJlnH8pzQGlHlBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rss899lzcafjv5y8ve8cj4urhqfyypwrlqua2jmeyusmkdmugdxqsluwyl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZGZRK2JwUWtrQWpCRlBy
            VkpJa1JPaUZQSHdBZWVjdE5vc09ZVTRPdzNvCitJdG5icm9ySFhnVVB5Rkk0aTFx
            SE4wbXArTTVremZmdkxjUTdYMEF3UUUKLS0tIGJlV0V0aTZGeWhuOXdQd21aMzVO
            ayttc0ptbUtKenkrL0IvUlNJMGtLUmsKobPvLR5ozT9Wqr6TfnY/Ym4TNkN89G5J
            bzCMcj3BnULEqf/lw6ZNAPOrlWdv5amrmxfebnEePXdmjiTyqSCGfQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zt22uns634n9qxy34jjjp86cw5ruynpngge0ypdere8kq40ysylqh6ce5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMVEzS0dKTUhab3pYNGhJ
            QkI3UU00SkhJMXAvekw5LzkvTmdwTXg5RVFjCjVJUFJXS1NwNlZWMHZPVXNBbHRY
            SEpnSlp0U1p1WXg2VExwMkQ5NWpoS00KLS0tIGFDNmlMZVhWL0x1L2tsc0l3WTRI
            Tkcxb25QanpsK1RvNVdrVzZiem5iTWsKQt0ifJ/rQZyh8LGK1tdeVmVdTG1RVMGy
            UcyPwYV4VgqfhkoYqBfX+3ttLRLw+/yUl4YGj5Hhy95+OSL3655XTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-26T07:09:48Z"
    mac: ENC[AES256_GCM,data:0jNq4zmUUgB8/bHDPWHnrJMjlFaAcCjEXcPAIWkJwifOVvi2tNJSsHYL24sfVecbPlobQV8jIDZ7FMk54iYUWKffbrcGojeTE78CPtKa/xexv2cqAnVYFCiBJ1AHkOrqCJ5jB9Go79/hW35+b2hHbEzpV41TltOKETNcQ2+RTkk=,iv:kILN/IOPhqgEL2yENDS4nPnWQAPkEs8ChzrVbfzgQ4Y=,tag:UX70aRfbn4K7CyN8naZkJA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
