---
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
radarr:
  hd:
    base_url: http://radarr-hd.downloads.svc.cluster.local
    api_key: !env_var RADARR_MOVIES_API_KEY
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    include:
      - template: radarr-quality-definition-sqp-streaming
      - template: radarr-quality-profile-sqp-1-web-1080p
      - template: radarr-custom-formats-sqp-1-web-1080p
    quality_profiles:
      - name: SQP-1 WEB (1080p)
        # min_format_score: 10 # Uncomment if indexers are not up to snuff
    custom_formats:
      - trash_ids:
          # Miscellaneous
          - b6832f586342ef70d9c128d40c07b872  # Bad Dual Groups
          - cc444569854e9de0b084ab2b8b1532b2  # Black and White Editions
          - 90cedc1fea7ea5d11298bebd3d1d3223  # EVO (no WEBDL)
          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5  # No-RlsGroup
          - 7357cf5161efbf8c4d5d0c30b4815ee2  # Obfuscated
          - 5c44f52a8714fdd79bb4d98e2673be1f  # Retags
          - f537cf427b64c38c8e36298f657e4828  # Scene

          # Movie Versions
          - 570bc9ebecd92723d2d21500f4be314c  # Remaster
          - eca37840c13c6ef2dd0262b141a5482f  # 4K Remaster
          - e0c07d59beb37348e975a930d5e50319  # Criterion Collection
          - 9d27d9d2181838f76dee150882bdc58c  # Masters of Cinema
          - db9b4c4b53d312a3ca5f1378f6440fc9  # Vinegar Syndrome
          - 957d0f44b592285f26449575e8b1167e  # Special Edition
        assign_scores_to:
          - name: SQP-1 WEB (1080p)

  uhd:
    base_url: http://radarr-uhd.downloads.svc.cluster.local
    api_key: !env_var RADARR_HQ_API_KEY
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    include:
      - template: radarr-quality-definition-sqp-uhd
      - template: radarr-quality-profile-sqp-3
      - template: radarr-custom-formats-sqp-3
      - template: radarr-quality-profile-sqp-4
      - template: radarr-custom-formats-sqp-4
      - template: radarr-quality-profile-sqp-2
      - template: radarr-custom-formats-sqp-2
    quality_profiles:
      - name: SQP-3
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: true
          until_quality: WEB|Remux|2160p
          until_score: 10000
        min_format_score: 3350
        score_set: sqp-3
        quality_sort: top
        qualities:
          - name: WEB|Remux|2160p
            qualities:
              - WEBDL-2160p
              - WEBRip-2160p
              - Remux-2160p
              - WEBDL-1080p
              - WEBRip-1080p
              - Remux-1080p
    custom_formats:
      - trash_ids:
          # Movie Versions
          - 0f12c086e289cf966fa5948eac571f44  # Hybrid
          - 570bc9ebecd92723d2d21500f4be314c  # Remaster
          - eca37840c13c6ef2dd0262b141a5482f  # 4K Remaster
          - e0c07d59beb37348e975a930d5e50319  # Criterion Collection
          - 9d27d9d2181838f76dee150882bdc58c  # Masters of Cinema
          - db9b4c4b53d312a3ca5f1378f6440fc9  # Vinegar Syndrome
          - 957d0f44b592285f26449575e8b1167e  # Special Edition
          - eecf3a857724171f968a66cb5719e152  # IMAX
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de  # IMAX Enhanced

          # Miscellaneous
          - b6832f586342ef70d9c128d40c07b872  # Bad Dual Groups
          - cc444569854e9de0b084ab2b8b1532b2  # Black and White Editions
          - 90cedc1fea7ea5d11298bebd3d1d3223  # EVO (no WEBDL)
          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5  # No-RlsGroup
          - 7357cf5161efbf8c4d5d0c30b4815ee2  # Obfuscated
          - 5c44f52a8714fdd79bb4d98e2673be1f  # Retags
          - f537cf427b64c38c8e36298f657e4828  # Scene

          # Only grab WEBDL w/ HDR10 fallback
          - 923b6abef9b17f937fab56cfcf89e1f1  # DV (WEBDL)

          # Grab HDR10+
          - b17886cb4158d9fea189859409975758  # HDR10+ Boost
          - 55a5b50cb416dea5a50c4955896217ab  # DV HDR10+ Boost

          # Block UHD/4k Remux and Bluray encode SDR releases, but allow SDR WEB
          - 25c12f78430a3a23413652cbd1d48d77  # SDR (no WEBDL)
        assign_scores_to:
          - name: SQP-2
          - name: SQP-3
          - name: SQP-4
