---
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
radarr:
  streaming:
    base_url: http://radarr-movies.downloads.svc.cluster.local
    api_key: !env_var RADARR_MOVIES_API_KEY
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    media_naming:
      folder: plex
      movie:
        rename: true
    include:
      - template: radarr-quality-definition-sqp-streaming
      - template: radarr-quality-profile-sqp-1-web-1080p
      - template: radarr-custom-formats-sqp-1-web-1080p
    custom_formats:
      - trash_ids:
          # Miscellaneous
          - b6832f586342ef70d9c128d40c07b872  # Bad Dual Groups
          - cc444569854e9de0b084ab2b8b1532b2  # Black and White Editions
          - 90cedc1fea7ea5d11298bebd3d1d3223  # EVO (no WEBDL)
          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5  # No-RlsGroup
          - 7357cf5161efbf8c4d5d0c30b4815ee2  # Obfuscated
          - 5c44f52a8714fdd79bb4d98e2673be1f  # Retags
          - f537cf427b64c38c8e36298f657e4828  # Scene

          # Movie Versions
          - 570bc9ebecd92723d2d21500f4be314c  # Remaster
          - eca37840c13c6ef2dd0262b141a5482f  # 4K Remaster
          - e0c07d59beb37348e975a930d5e50319  # Criterion Collection
          - 9d27d9d2181838f76dee150882bdc58c  # Masters of Cinema
          - db9b4c4b53d312a3ca5f1378f6440fc9  # Vinegar Syndrome
          - 957d0f44b592285f26449575e8b1167e  # Special Edition
        assign_scores_to:
          - name: SQP-1 WEB (1080p)
