---
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
sonarr:
  tv:
    base_url: http://sonarr-tv.downloads.svc.cluster.local
    api_key: !env_var SONARR_TV_API_KEY
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    media_naming:
      series: plex
      episodes:
        rename: true
    include:
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-quality-profile-web-1080p-alternative
      - template: sonarr-v4-custom-formats-web-1080p
      - template: sonarr-v4-quality-profile-web-2160p-alternative
      - template: sonarr-v4-custom-formats-web-2160p
    custom_formats:
      # Optional
      - trash_ids:
          - 32b367365729d530ca1c124a0b180c64  # Bad Dual Groups
          - 82d40da2bc6923f41e14394075dd4b03  # No-RlsGroup
          - e1a997ddb54e3ecbfe06341ad323c458  # Obfuscated
          - 06d66ab109d4d2eddb2794d21526d140  # Retags
        assign_scores_to:
          - name: WEB-1080p
          - name: WEB-2160p
      - trash_ids:
          - 1b3994c551cbb92a2c781af061f4ab44  # Scene
        assign_scores_to:
          - name: WEB-1080p
            score: 0
          - name: WEB-2160p
            score: 0

      # HDR Formats
      - trash_ids:
          - 9b27ab6498ec0f31a3353992e19434ca  # DV (WEBDL)
          - 0dad0a507451acddd754fe6dc3a7f5e7  # HDR10+ Boost
          - 385e9e8581d33133c3961bdcdeffb7b4  # DV HDR10+ Boost
        assign_scores_to:
          - name: WEB-2160p
