---
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
sonarr:
  sonarr_anime:
    base_url: http://sonarr-anime.downloads.svc.cluster.local
    api_key: !env_var SONARR_ANIME_API_KEY
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    media_naming:
      series: plex
      episodes:
        rename: true
    include:
      - template: sonarr-quality-definition-anime
      - template: sonarr-v4-quality-profile-anime
      - template: sonarr-v4-custom-formats-anime
    custom_formats:
      - trash_ids:
          - 418f50b10f1907201b6cfdf881f467b7  # Anime Dual Audio
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: -100 # Discourage dual audio downloads
