---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr-anime
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sonarr-anime-secret
    template:
      engineVersion: v2
      data:
        SONARR__API_KEY: "{{ .SONARR_ANIME_API_KEY }}"
        SONARR__POSTGRES_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        SONARR__POSTGRES_PORT: "5432"
        SONARR__POSTGRES_USER: &dbUser "{{ .SONARR_ANIME_POSTGRES_USER }}"
        SONARR__POSTGRES_PASSWORD: &dbPass "{{ .SONARR_ANIME_POSTGRES_PASSWORD }}"
        SONARR__POSTGRES_MAIN_DB: sonarr_anime_main
        SONARR__POSTGRES_LOG_DB: sonarr_anime_log
        INIT_POSTGRES_DBNAME: sonarr_anime_main sonarr_anime_log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: sonarr