---
originRequest:
  originServerName: external.kyle.fail

ingress:
  - hostname: kyle.fail
    service: https://external-ingress-nginx-controller.network.svc.cluster.local:443
  - hostname: "*.kyle.fail"
    service: https://external-ingress-nginx-controller.network.svc.cluster.local:443
  - service: http_status:404
