kavita:
  eventListener:
    enabled: true
    metadataLibraryFilter:
      - 1 # Manga
      - 2 # Light Novels
  metadataUpdate:
    default:
      updateModes: [ API ]
      aggregate: true
      mergeTags: true
      mergeGenres: true
      bookCovers: true
      seriesCovers: true
      postProcessing:
        seriesTitle: true
        seriesTitleLanguage: "en"
        alternativeSeriesTitles: false
        alternativeSeriesTitleLanguages:
          - "en"
          - "ja"
          - "ja-ro"
        orderBooks: true
        scoreTag: true
      library:
        1:
          mediaType: MANGA
        2:
          mediaType: NOVEL

database:
  file: ./database.sqlite

metadataProviders:
  malClientId: "${SECRET_KOMF_MAL_CLIENT_ID}" # required for mal provider. See https://myanimelist.net/forum/?topicid=1973077
  defaultProviders:
    mangaUpdates:
      priority: 10
      enabled: true
      mediaType: MANGA
      authorRoles: [ "WRITER" ]
      artistRoles: [ "PENCILLER","INKER","COLORIST","LETTERER","COVER" ]
    mal:
      priority: 20
      enabled: true
      mediaType: MANGA
    nautiljon:
      priority: 30
      enabled: true
