---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: nas
  labels:
    app.kubernetes.io/name: nas
    app.kubernetes.io/instance: nas
    target-dns: internal
spec:
  endpoints:
    - dnsName: tank.kyle.fail
      recordType: A
      targets: ["192.168.10.5"]
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.29.0/service.json
apiVersion: v1
kind: Service
metadata:
  name: nas
  labels:
    app.kubernetes.io/name: nas
    app.kubernetes.io/instance: nas
spec:
  type: ExternalName
  externalName: tank.kyle.fail
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.29.0/ingress.json
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nas
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  labels:
    app.kubernetes.io/name: nas
    app.kubernetes.io/instance: nas
spec:
  ingressClassName: internal
  rules:
    - host: &host nas.kyle.fail
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nas
                port:
                  number: 80
  tls:
    - hosts:
        - *host